apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ai-app.fullname" . }}
  labels:
    {{- include "ai-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: ai-app
          image: ""
          ports:
            - containerPort: 11434 