apiVersion: v1 
kind: Service 
metadata:
  name: ai-app-svc
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 11434
  selector:
    app: ai-app

